examples_url: https://github.com/alsgh5016/kafl.targets
examples_root: "{{ kafl_install_root }}/examples"
examples_revision: "v0.3"

dvkm_sub_path: linux-user/dvkm/Damn_Vulnerable_Kernel_Module
linux_agent_sub_path: linux-user/linux_kafl_agent
