name: Security
permissions: {}

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
    paths-ignore:
      - '**/README.md'
      - '.github/RELEASE.md'
  pull_request:
    paths-ignore:
      - '**/README.md'
      - '.github/RELEASE.md'

jobs:
  snyk-lint-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        req_path: ["deploy/requirements.txt", "docs/requirements.txt"]
      fail-fast: false
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6
        with:
          python-version: 3.11

      - name: install dependencies
        run: pip install -r ${{ matrix.req_path }}

      - name: Copy requirements.txt at root of GITHUB_WORKSPACE for Snyk
        run: cp ${{ matrix.req_path }} .

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@e2221410bff24446ba09102212d8bc75a567237d # v1.0.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
        continue-on-error: true
      #     args: --sarif-file-output=snyk.sarif
      

      # - name: Upload result to GitHub Code Scanning
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     sarif_file: snyk.sarif

  hadolint:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

        - name: Lint Dockerfile
          id: hadolint
          uses: hadolint/hadolint-action@4b5806eb9c6bee4954fc0e0cc3ad6175fc9782c1 # v3.0.0
          with:
            # only consider errors, not warning or info level
            failure-threshold: error
            output-file: ${{ github.workspace }}/hadolint.out
          continue-on-error: true

        - name: Upload hadolint output artifact
          uses: actions/upload-artifact@v4.4.3
          with:
            name: hadolint
            path: ${{ github.workspace }}/hadolint.out
